### ISSUE TITLE
KeyError: 'Non-existent config key: TRAIN.RANK_CLS_WEIGHT'

### ISSUE THREAD

**Issue by DYF981109** [sansanfree/RBO#10]
Traceback (most recent call last):
  File "/home/s321087014/CODE/PythonCode/RBO/RBO-main/SiamRPN++-RBO/tools/train.py", line 313, in <module>
    main()
  File "/home/s321087014/CODE/PythonCode/RBO/RBO-main/SiamRPN++-RBO/tools/train.py", line 255, in main
    cfg.merge_from_file(args.cfg)
  File "/home/s321087014/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/s321087014/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/s321087014/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/s321087014/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: TRAIN.RANK_CLS_WEIGHT'
我在用单个数据集VID训练SiamRPN++-RBO时碰到了这个问题，请问该怎么解决啊。

**Comment by sansanfree** [comment]
1.你好，你检查一下RBO\SiamRPN++-RBO\pysot\core\config.yaml 有没有 __C.TRAIN.RANK_CLS_WEIGHT = 0.5。
。我记得是有的。如果正常有的话，我猜测原因，你pysot环境用的是siamrpn++的，siamrpn++中的pysot是没有TRAIN.RANK_CLS_WEIGHT'的。建议，你pysot环境用本项目中的。
2.不建议用VID一个数据集来训练siamrpn系列的跟踪器，是训练不出来的，从最早的SiamRPN,到SiamRPN++再到后面其他衍生跟踪器，最少的数据集组合应该是VID+Yutube BB，建议还是保持5个数据集。

**Comment by DYF981109** [comment]
> 1.你好，你检查一下RBO\SiamRPN++-RBO\pysot\core\config.yaml 有没有 __C.TRAIN.RANK_CLS_WEIGHT = 0.5。 。我记得是有的。如果正常有的话，我猜测原因，你pysot环境用的是siamrpn++的，siamrpn++中的pysot是没有TRAIN.RANK_CLS_WEIGHT'的。建议，你pysot环境用本项目中的。 2.不建议用VID一个数据集来训练siamrpn系列的跟踪器，是训练不出来的，从最早的SiamRPN,到SiamRPN++再到后面其他衍生跟踪器，最少的数据集组合应该是VID+Yutube BB，建议训练SiamRPN++-RBO还是保持5个数据集。

你好，我之前确实是用的SiamRPN++的环境，而且RBO\SiamRPN++-RBO\pysot\core\config.yaml 中是有 __C.TRAIN.RANK_CLS_WEIGHT = 0.5的。后来我重新下载了代码且按照本项目的INSTALL.md安装了环境，但是还是跟之前一样报错KeyError: 'Non-existent config key: TRAIN.RANK_CLS_WEIGHT' 。

**Comment by sansanfree** [comment]
> > 1.你好，你检查一下RBO\SiamRPN++-RBO\pysot\core\config.yaml 有没有 __C.TRAIN.RANK_CLS_WEIGHT = 0.5。 。我记得是有的。如果正常有的话，我猜测原因，你pysot环境用的是siamrpn++的，siamrpn++中的pysot是没有TRAIN.RANK_CLS_WEIGHT'的。建议，你pysot环境用本项目中的。 2.不建议用VID一个数据集来训练siamrpn系列的跟踪器，是训练不出来的，从最早的SiamRPN,到SiamRPN++再到后面其他衍生跟踪器，最少的数据集组合应该是VID+Yutube BB，建议训练SiamRPN++-RBO还是保持5个数据集。
> 
> 你好，我之前确实是用的SiamRPN++的环境，而且RBO\SiamRPN++-RBO\pysot\core\config.yaml 中是有 __C.TRAIN.RANK_CLS_WEIGHT = 0.5的。后来我重新下载了代码且按照本项目的INSTALL.md安装了环境，但是还是跟之前一样报错KeyError: 'Non-existent config key: TRAIN.RANK_CLS_WEIGHT' 。

你重新执行一下：export PYTHONPATH=/你的路径SiamRPN++-RBO:$PYTHONPATH，看看行不行。

**Comment by DYF981109** [comment]
> 

不行，还是相同的报错。

**Comment by DYF981109** [comment]
> > > 1.你好，你检查一下RBO\SiamRPN++-RBO\pysot\core\config.yaml 有没有 __C.TRAIN.RANK_CLS_WEIGHT = 0.5。 。我记得是有的。如果正常有的话，我猜测原因，你pysot环境用的是siamrpn++的，siamrpn++中的pysot是没有TRAIN.RANK_CLS_WEIGHT'的。建议，你pysot环境用本项目中的。 2.不建议用VID一个数据集来训练siamrpn系列的跟踪器，是训练不出来的，从最早的SiamRPN,到SiamRPN++再到后面其他衍生跟踪器，最少的数据集组合应该是VID+Yutube BB，建议训练SiamRPN++-RBO还是保持5个数据集。
> > 
> > 
> > 你好，我之前确实是用的SiamRPN++的环境，而且RBO\SiamRPN++-RBO\pysot\core\config.yaml 中是有 __C.TRAIN.RANK_CLS_WEIGHT = 0.5的。后来我重新下载了代码且按照本项目的INSTALL.md安装了环境，但是还是跟之前一样报错KeyError: 'Non-existent config key: TRAIN.RANK_CLS_WEIGHT' 。
> 
> 你重新执行一下：export PYTHONPATH=/你的路径SiamRPN++-RBO:$PYTHONPATH，看看行不行。

不行，还是相同的报错。

**Comment by sansanfree** [comment]
> > > > 1.你好，你检查一下RBO\SiamRPN++-RBO\pysot\core\config.yaml 有没有 __C.TRAIN.RANK_CLS_WEIGHT = 0.5。 。我记得是有的。如果正常有的话，我猜测原因，你pysot环境用的是siamrpn++的，siamrpn++中的pysot是没有TRAIN.RANK_CLS_WEIGHT'的。建议，你pysot环境用本项目中的。 2.不建议用VID一个数据集来训练siamrpn系列的跟踪器，是训练不出来的，从最早的SiamRPN,到SiamRPN++再到后面其他衍生跟踪器，最少的数据集组合应该是VID+Yutube BB，建议训练SiamRPN++-RBO还是保持5个数据集。
> > > 
> > > 
> > > 你好，我之前确实是用的SiamRPN++的环境，而且RBO\SiamRPN++-RBO\pysot\core\config.yaml 中是有 __C.TRAIN.RANK_CLS_WEIGHT = 0.5的。后来我重新下载了代码且按照本项目的INSTALL.md安装了环境，但是还是跟之前一样报错KeyError: 'Non-existent config key: TRAIN.RANK_CLS_WEIGHT' 。
> > 
> > 
> > 你重新执行一下：export PYTHONPATH=/你的路径SiamRPN++-RBO:$PYTHONPATH，看看行不行。
> 
> 不行，还是相同的报错。

在train.py代码中，你看看24行到33行的pysot指向哪里，你可能在这个环境中，安装pysot了吗（通过pip install）。是的话，卸载。或者换一个环境，执行RBO

**Comment by DYF981109** [comment]
> > > > > 1.你好，你检查一下RBO\SiamRPN++-RBO\pysot\core\config.yaml 有没有 __C.TRAIN.RANK_CLS_WEIGHT = 0.5。 。我记得是有的。如果正常有的话，我猜测原因，你pysot环境用的是siamrpn++的，siamrpn++中的pysot是没有TRAIN.RANK_CLS_WEIGHT'的。建议，你pysot环境用本项目中的。 2.不建议用VID一个数据集来训练siamrpn系列的跟踪器，是训练不出来的，从最早的SiamRPN,到SiamRPN++再到后面其他衍生跟踪器，最少的数据集组合应该是VID+Yutube BB，建议训练SiamRPN++-RBO还是保持5个数据集。
> > > > 
> > > > 
> > > > 你好，我之前确实是用的SiamRPN++的环境，而且RBO\SiamRPN++-RBO\pysot\core\config.yaml 中是有 __C.TRAIN.RANK_CLS_WEIGHT = 0.5的。后来我重新下载了代码且按照本项目的INSTALL.md安装了环境，但是还是跟之前一样报错KeyError: 'Non-existent config key: TRAIN.RANK_CLS_WEIGHT' 。
> > > 
> > > 
> > > 你重新执行一下：export PYTHONPATH=/你的路径SiamRPN++-RBO:$PYTHONPATH，看看行不行。
> > 
> > 
> > 不行，还是相同的报错。
> 
> 在train.py代码中，你看看24行到33行的pysot指向哪里，你可能在这个环境中，安装pysot了吗（通过pip install）。是的话，卸载。或者换一个环境，执行RBO

我看了下train.py里的24行到33行代码，好像是没什么问题。
from pysot.utils.lr_scheduler import build_lr_scheduler
from pysot.utils.log_helper import init_log, print_speed, add_file_handler
from pysot.utils.distributed import dist_init, DistModule, reduce_gradients,\
        average_reduce, get_rank, get_world_size
from pysot.utils.model_load import load_pretrain, restore_from
from pysot.utils.average_meter import AverageMeter
from pysot.utils.misc import describe, commit
from pysot.models.model_builder import ModelBuilder
from pysot.datasets.dataset import TrkDataset
from pysot.core.config import cfg
后来我在另一个环境试了下，还是报这个错误KeyError: 'Non-existent config key: TRAIN.RANK_CLS_WEIGHT'

**Comment by sansanfree** [comment]
1.你看一下你的代码中，from pysot.core.config import cfg这行，config指向哪里。我觉得是指向你的环境变量。
python
import sys
print(sys.path) 看看路径中有没有pysot,有就删除。

2.如果还是不行的话，在tools/test.py,train.py,eval.py  开头中加入以下命令，在运行。

import os.path as osp
import sys 
module_name = "main"
p = __file__
while osp.basename(p) != module_name:
    p = osp.dirname(p)
ROOT_PATH = osp.dirname(p)
sys.path.insert(0, ROOT_PATH)  # isort:skip

**Comment by DYF981109** [comment]
- > 1.在print(sys.path)输出中有'/home/s321087014/CODE/PythonCode/pysot-master'，我在train.py中加入
- sys.path.remove("/home/s321087014/CODE/PythonCode/pysot-master")；print(sys.path)  再运行
-   FutureWarning,
['/home/s321087014/CODE/PythonCode/RBO-main/SiamRPN++-RBO/tools', '/home/s321087014/CODE/PythonCode/RBO-main/SiamRPN++-RBO', '/home/s321087014/CODE/PythonCode/RBO-main/SiamRPN++-RBO/experiments/train/fulldata', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python37.zip', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python3.7', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python3.7/lib-dynload', '/home/s321087014/.local/lib/python3.7/site-packages', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python3.7/site-packages']
路径中没有pysot-master了但是不行。

2.不知是不是我添加的方式不对，我在train.py中加入
import os.path as osp
import sys
module_name = "main"
p = __file__
while osp.basename(p) != module_name:
    p = osp.dirname(p)
    ROOT_PATH = osp.dirname(p)
    sys.path.insert(0, ROOT_PATH)
再运行服务器就直接卡住了。

**Comment by DYF981109** [comment]
> 1.你看一下你的代码中，from pysot.core.config import cfg这行，config指向哪里。我觉得是指向你的环境变量。 python import sys print(sys.path) 看看路径中有没有pysot,有就删除。
> 
> 2.如果还是不行的话，在tools/test.py,train.py,eval.py 开头中加入以下命令，在运行。
> 
> `import os.path as osp import sys module_name = "main" p = __file__ while osp.basename(p) != module_name: p = osp.dirname(p) ROOT_PATH = osp.dirname(p) sys.path.insert(0, ROOT_PATH) `

1.在print(sys.path)输出中有'/home/s321087014/CODE/PythonCode/pysot-master'，我在train.py中加入
sys.path.remove("/home/s321087014/CODE/PythonCode/pysot-master")    print(sys.path) 再运行
FutureWarning,
['/home/s321087014/CODE/PythonCode/RBO-main/SiamRPN++-RBO/tools', '/home/s321087014/CODE/PythonCode/RBO-main/SiamRPN++-RBO', '/home/s321087014/CODE/PythonCode/RBO-main/SiamRPN++-RBO/experiments/train/fulldata', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python37.zip', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python3.7', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python3.7/lib-dynload', '/home/s321087014/.local/lib/python3.7/site-packages', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python3.7/site-packages']
路径中没有pysot-master了但是不行。
2.不知是不是我添加的方式不对，我在train.py中加入
import os.path as osp
import sys
module_name = "main"
p = file
while osp.basename(p) != module_name:
      p = osp.dirname(p)
      ROOT_PATH = osp.dirname(p)
      sys.path.insert(0, ROOT_PATH)
再运行服务器就直接卡住了。

**Comment by DYF981109** [comment]
> 1.你看一下你的代码中，from pysot.core.config import cfg这行，config指向哪里。我觉得是指向你的环境变量。 python import sys print(sys.path) 看看路径中有没有pysot,有就删除。
> 
> 2.如果还是不行的话，在tools/test.py,train.py,eval.py 开头中加入以下命令，在运行。
> 
> `import os.path as osp import sys module_name = "main" p = __file__ while osp.basename(p) != module_name: p = osp.dirname(p) ROOT_PATH = osp.dirname(p) sys.path.insert(0, ROOT_PATH) `

1.在print(sys.path)输出中有'/home/s321087014/CODE/PythonCode/pysot-master'，我在train.py中加入
sys.path.remove("/home/s321087014/CODE/PythonCode/pysot-master")    print(sys.path) 再运行
FutureWarning,
['/home/s321087014/CODE/PythonCode/RBO-main/SiamRPN++-RBO/tools', '/home/s321087014/CODE/PythonCode/RBO-main/SiamRPN++-RBO', '/home/s321087014/CODE/PythonCode/RBO-main/SiamRPN++-RBO/experiments/train/fulldata', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python37.zip', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python3.7', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python3.7/lib-dynload', '/home/s321087014/.local/lib/python3.7/site-packages', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python3.7/site-packages']
路径中没有pysot-master了但是不行。
2.不知是不是我添加的方式不对，我在train.py中加入
import os.path as osp
import sys
module_name = "main"
p = file
while osp.basename(p) != module_name:
[TAB]p = osp.dirname(p)
[TAB]ROOT_PATH = osp.dirname(p)
[TAB]sys.path.insert(0, ROOT_PATH)
再运行服务器就直接卡住了。

**Comment by sansanfree** [comment]
抱歉，刚才代码贴错了

`import os.path as osp

import sys  # isort:skip

module_name = "tools"
p = __file__

while osp.basename(p) != module_name:
    p = osp.dirname(p)   

ROOT_PATH = osp.dirname(p)
sys.path.insert(0, ROOT_PATH)  
`

**Comment by sansanfree** [comment]
> > 1.你看一下你的代码中，from pysot.core.config import cfg这行，config指向哪里。我觉得是指向你的环境变量。 python import sys print(sys.path) 看看路径中有没有pysot,有就删除。
> > 2.如果还是不行的话，在tools/test.py,train.py,eval.py 开头中加入以下命令，在运行。
> > `import os.path as osp import sys module_name = "main" p = __file__ while osp.basename(p) != module_name: p = osp.dirname(p) ROOT_PATH = osp.dirname(p) sys.path.insert(0, ROOT_PATH) `
> 
> 1.在print(sys.path)输出中有'/home/s321087014/CODE/PythonCode/pysot-master'，我在train.py中加入 sys.path.remove("/home/s321087014/CODE/PythonCode/pysot-master") print(sys.path) 再运行 FutureWarning, ['/home/s321087014/CODE/PythonCode/RBO-main/SiamRPN++-RBO/tools', '/home/s321087014/CODE/PythonCode/RBO-main/SiamRPN++-RBO', '/home/s321087014/CODE/PythonCode/RBO-main/SiamRPN++-RBO/experiments/train/fulldata', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python37.zip', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python3.7', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python3.7/lib-dynload', '/home/s321087014/.local/lib/python3.7/site-packages', '/home/s321087014/anaconda3/envs/pysot-RBO/lib/python3.7/site-packages'] 路径中没有pysot-master了但是不行。 2.不知是不是我添加的方式不对，我在train.py中加入 import os.path as osp import sys module_name = "main" p = file while osp.basename(p) != module_name: [TAB]p = osp.dirname(p) [TAB]ROOT_PATH = osp.dirname(p) [TAB]sys.path.insert(0, ROOT_PATH) 再运行服务器就直接卡住了。

`import os.path as osp

import sys  # isort:skip

module_name = "tools"
p = __file__

while osp.basename(p) != module_name:
    p = osp.dirname(p)   

ROOT_PATH = osp.dirname(p)
sys.path.insert(0, ROOT_PATH)  
`

**Comment by DYF981109** [comment]
> 在train.py中加入代码后还是不行
import os.path as osp
import sys
module_name = "tools"
p = __file__
while osp.basename(p) != module_name:
[TAB]p = osp.dirname(p)
[TAB]ROOT_PATH = osp.dirname(p)
[TAB]sys.path.insert(0, ROOT_PATH)

**Comment by DYF981109** [comment]
问题解决了，之前我改完.bashrc文件注释掉pysot路径是用source  ~/.bashrc指令来生效，但是不知为什么没生效，这次我重启了一下服务器发现问题解决了。万分感谢作者大大热情指导。

**Comment by sansanfree** [comment]
> 问题解决了，之前我改完.bashrc文件注释掉pysot路径是用source ~/.bashrc指令来生效，但是不知为什么没生效，这次我重启了一下服务器发现问题解决了。万分感谢作者大大热情指导。

不客气，有啥其他问题，欢迎提问。
