### ISSUE TITLE
在test.py测试OTB100时出现问题

### ISSUE THREAD

**Issue by smilingChen** [sansanfree/RBO#14]

**Comment by smilingChen** [comment]
checkpoints/SiamRPN++-RBO-general-OTNV.pth
loading OTB100: 100%|███████████████████████████████████████| 98/98 [00:00<00:00, 142.85it/s, Woman]
(  1) Video: Basketball   Time: 744.1s Speed: 1.0fps
(  2) Video: Biker        Time:   1.5s Speed: 93.3fps
D:/code/RBO-main/SiamRPN++-RBO\pysot\tracker\siamrpn_tracker.py:125: RuntimeWarning: overflow encountered in multiply
  return np.sqrt((w + pad) * (h + pad))

出现了以上的情况，且输出的.txt文件均为错误位置，请问这是什么情况？比较困扰

**Comment by sansanfree** [comment]
> checkpoints/SiamRPN++-RBO-general-OTNV.pth loading OTB100: 100%|███████████████████████████████████████| 98/98 [00:00<00:00, 142.85it/s, Woman] ( 1) Video: Basketball Time: 744.1s Speed: 1.0fps ( 2) Video: Biker Time: 1.5s Speed: 93.3fps D:/code/RBO-main/SiamRPN++-RBO\pysot\tracker\siamrpn_tracker.py:125: RuntimeWarning: overflow encountered in multiply return np.sqrt((w + pad) * (h + pad))
> 
> 出现了以上的情况，且输出的.txt文件均为错误位置，请问这是什么情况？比较困扰

你可以调试一下，我猜测是数据集格式不太对，未能正确读进来图片路径和ground truth,你检查一下读的正不正确。

**Comment by smilingChen** [comment]
@sansanfree 谢谢作者提供的建议，问题解决
