### ISSUE TITLE
计算IGR_loss时，pred_bboxes = self.convert_bbox(loc, point_tensor)的convert_bbox的计算过程可以大概讲一下吗？

### ISSUE THREAD

**Issue by lihao0lihao** [sansanfree/RBO#15]

**Comment by lihao0lihao** [comment]
points在这里是什么作用？

**Comment by sansanfree** [comment]
这里采用的是FCOS检测器（ICCV2019）的anchor-free范式，self.convert_bbox(loc, point_tensor)中，loc代表预测点points离矩形框的left、 top、bottom和right四条边的距离。更多细节请看FCOS论文。

**Comment by lihao0lihao** [comment]
感谢您的回复！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sansanfree/RBO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 中午12:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sansanfree/RBO] 计算IGR_loss时，pred_bboxes = self.convert_bbox(loc, point_tensor)的convert_bbox的计算过程可以大概讲一下吗？ (Issue #15)





 
这里采用的是FCOS检测器（ICCV2019）的anchor-free范式，self.convert_bbox(loc, point_tensor)中，loc代表预测点points离矩形框的left、 top、bottom和right四条边的距离。更多细节请看FCOS论文。
