### ISSUE TITLE
代码测试中的问题

### ISSUE THREAD

**Issue by DDuranin** [sansanfree/RBO#6]
按照你的readme.md测试GOT数据集时，代码读取了所有测试集，但只测试最后两个。在测试UAV123以及LaSOT等其他数据集时，代码只会读取数据集，不进行测试。请问这是为什么呢？我通过单步调节发现确实读取了测试集，就没有进行后续的运算。请问这是为什么呢？

**Comment by sansanfree** [comment]
抱歉，我上次上传的代码有一些小问题，我做了修改。https://github.com/sansanfree/RBO/commit/0d9c86ce47e8a98e4fbec41dd367dfa7fa409c12
我测试了是没问题，你看看。

**Comment by DDuranin** [comment]
非常感谢您的修改。我测试了更改后的代码，各数据集结果与您论文结果相近。
